//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactsAspMvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Email
    {
        [Key]
        public int EmailId { get; set; }
        public int ContactId { get; set; }
        [DataType(DataType.EmailAddress)]
        [Required]
        [Display(Name ="Endereço de E-mail")]
        public string EmailAddress { get; set; }
        [Required]
        [Display(Name = "Tipo de E-mail")]
        public int EmailTypeId { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual EmailType EmailType { get; set; }
    }
}
